### PR TITLE
Added 8 buttons as maximum per width on tablet.html (backport)

### PR DESCRIPTION
**Pull request by GeoDerp**
## Added 8 buttons as maximum per width
Requested by: https://github.com/bitfocus/companion/pull/806#issuecomment-528705414
Adds a maximum limit of 8 buttons wide (like an *Elgato Stream Deck XL*). 

**Large Screen Example:**
Large Screen Example
*This image is showing the master branch version, will make a backport image version when I can*

Thanks to **[ChrisRowtcliff](https://github.com/ChrisRowtcliff)**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;With some web dev help.

### CODE REVIEW

**Comment by willosof** [comment]
Backport doesn't support XL sizes. You should push this to master?

**Comment by GeoDerp** [comment]
> Backport doesn't support XL sizes. You should push this to master?

@willosof The code should'nt be scaling the button `size` at all it should only be forcing an max 8 row grid. So if you running a monitor larger than 8 buttons long, it will restrict the grid to only show 8 buttons long and 2 collumns *(like the example above just it will be 12 bay not 32)*

In saying that, I haven't been able to get nodejs to work on the backport version reasontley, so I haven't been able to test it. 

If you don't want it on the backport branch or it dosent work in any way let me know and ill close it. 
The master branch has already acceptted the pull request quite a while ago. :)

**Comment by JeffreyDavidsz** [comment]
Forgot to comment, I only pulled to master, because of the reason @willosof mentioned.

**Comment by GeoDerp** [comment]
After Thought, I don't think I will implement a max into backport, due to 12 banks being such a small amount.
But, If you want to make a max columns of 5 buttons (3 rows), like the standard StreamDeck just insert this into tablet.html:
``` html
.page {
			padding: 20px;				
			max-width: 1070px;
			margin: 0 auto;
		}			

```

Thanks 
        Geo Derp

**Pull request closed without merging**
