### PR TITLE
feat: ui improvements for pages editor

### PR DESCRIPTION
**Pull request by bryce-seifert**

### CODE REVIEW

**Comment by krocheck** [comment]
@bryce-seifert when submitting PRs, please include descriptions and screenshots (where applicable) of what the modifications are.

I'm not a fan of these changes, especially adding the text to the buttons.  Although it clarifies, its a deviation from how buttons of a similar nature are placed in other contexts IMO.  I do like the concept of the "Jump To" button instead of clicking the number.  That's definitely a worthwhile change.

**Comment by bryce-seifert** [comment]
Understood on images, I see how that can be helpful especially in a UI context.

I'll see if I can rework these to be more similar to other areas of Companion.

**Comment by Julusian** [comment]
Yeah, the lack of labels was intentional, for consistency with elsewhere. 
The navigating to the page on clicking the number I agree could be improved, I've forgotten thats a thing at times (and I forgot to change the style of it to match the other buttons)

Oh and yeah the icon being `faPaperPlane`, I feel like that was me picking something random while developing and forgetting to go back and change it..
For my current feature, i randomly chose `faDog`

**Comment by bryce-seifert** [comment]
Thanks for the feedback, I've reverted adding the text and tried to style more inline with the other UI buttons. Let me know how we feel about this:

Screenshot 2024-10-12 at 12 04 42 PM
Screenshot 2024-10-12 at 12 04 47 PM

**Comment by krocheck** [comment]
@Julusian I'm good with this now.

**Pull request merged**
