### PR TITLE
Updated "Getting Started" guide for Companion 2.2 with new UI

### PR DESCRIPTION
**Pull request by McHauge**

### CODE REVIEW

**Comment by krocheck** [comment]
Did you run prettier on this before committing?  `yarn format`

**Comment by McHauge** [comment]
No, but i can in a minute, just to clarify when should yarn format be run?

**Comment by krocheck** [comment]
It should be run before you commit changes for the core ... or it can be run after and committed separately

**Comment by McHauge** [comment]
superb, I'll note that for future use, it should be fixed now

**Pull request merged**
