### PR TITLE
feat: add rescan control to HTTP, TCP, UDP, OSC interfaces

### PR DESCRIPTION
**Pull request by llamafilm**
This should make it easier to integrate with other systems, related to #1274 and #481.

### CODE REVIEW

**Comment by llamafilm** [comment]
There's probably a more efficient way to do this natively within Companion, but I just wrote a quick and easy Python app that checks for new USB HID devices every second and then triggers a rescan.  Only tested on Windows.

```python
# Monitor for USB changes and trigger Companion rescan when Stream Deck is connected

import time
import hid
import requests

companion_url = 'http://127.0.0.1:8000'

def is_connected(already_connected):
    for d in hid.enumerate(vendor_id=4057):
        if 'Stream Deck' in d['product_string']:
            if already_connected:
                # it was already here
                return True
            else:
                # it was newly connected so trigger Companion
                print(f"Found {d['product_string']} - serial {d['serial_number']} - device ID {d['product_id']}")
                requests.get(companion_url + '/rescan')
                return True

    # it's not connected
    if already_connected:
        # it was just disconnected
        print('Stream Deck was disconnected.')
    
    # else it was never here
    return False


def main():
    connected = False
    
    while True:
        # look for Stream Deck every second
        connected = is_connected(connected)
        time.sleep(1)

main()
```

**Comment by krocheck** [comment]
@Julusian this will cause a merge conflict for #1844, which is OK and I will deal.  I'd rather that then putting this PR into conflict.

**Comment by krocheck** [comment]
@llamafilm [historically], the reason we don't do a periodic rescan is because it is a blocking action in the current architecture and therefore can interrupt precise timing/delays of a bank if it fires at the wrong time, a new device is detected, and syncs up.  Most computers that's not an issue, but Raspberry Pi's could have an issue.  This question has come up many times over the history of the app and I still stand by not doing that by default.  I'm now tempted to allow a user config option for users to turn on a periodic rescan and define the interval.  Thoughts @Julusian?

**Review by krocheck — APPROVED** [review]

**Review by krocheck — CHANGES_REQUESTED** [review]
On 2nd thought, @llamafilm  ... it seems like we have good parity of control between the HTTP, TCP/UDP, and OSC remote control protocols.  I'd like to see this implemented and documented across all of them instead of just HTTP.

**Comment by llamafilm** [comment]
Good point, here you go

**Comment by Julusian** [comment]
> @llamafilm [historically], the reason we don't do a periodic rescan is because it is a blocking action in the current architecture and therefore can interrupt precise timing/delays of a bank if it fires at the wrong time, a new device is detected, and syncs up. Most computers that's not an issue, but Raspberry Pi's could have an issue. This question has come up many times over the history of the app and I still stand by not doing that by default. I'm now tempted to allow a user config option for users to turn on a periodic rescan and define the interval. Thoughts @Julusian?

Yeah it is a blocking operation to scan for hid devices that could interrupt other things. A quick test on a pi zero w 2 that I have in front of me says it takes ~10ms to perform, excluding any time we will take to process the results of that.
So I believe that is the reason we don't scan on an interval right now. I have been very tempted to use a library to watch for new devices, and use that to trigger a rescan (like [companion-satellite](https://github.com/bitfocus/companion-satellite/blob/master/src/devices.ts#L32-L34) does), but the library for that is currently a little crash prone on linux, and is often slow at providing builds for new versions of node/electron (it held back companion-satellite on an older electron than companion for a few months).

I have a plan which has been discussed with maintainers for improving detection library. A brief summary is that [node-usb](https://github.com/node-usb/node-usb) already supports proper detection on every platform other than windows. on windows they are for now doing a slow poll. I intend to submit a PR to implement something proper. 
So I think we should use the watching feature of node-usb for the first implementation of auto-watching. If we make it opt-in and label it as experimental/unstable or a bunch of warnings, then its there for those who need it, but with no guarantees. Then one day that will be true watching on every os, without any extra work from us.
If we are concerned about performance impact of the watching or scanning, we could do like what is being done for the usb devices, and run the scans in a child process or worker thread. that may not completely avoid any impact, but will minimise it


As for adding these endpoints to the apis, I am fine with doing that. Its simple enough to not be a burden going forward, and allows for some other workflows (I think people do it today by having the scan triggered from a button, and using http/whatever to press that button)

**Comment by krocheck** [comment]
Thanks @llamafilm! Did you test the additional implementations?

@Julusian I'm good with your plan.

**Comment by istnv** [comment]
A while back I posted a set of `udev` rules that automatically run a rescan when a streamdeck is plugged in. 
It runs a shell script that 'pushes' a button with the re-scan action. Works great on Linux (ubuntu) and Raspberry Pi. This will remove the need to dedicate a button.

**Comment by krocheck** [comment]
> Thanks @llamafilm! Did you test the additional implementations?
> 
> @Julusian I'm good with your plan.

@llamafilm ... didn't answer my question above.  Please and thank you!

**Comment by llamafilm** [comment]
I already answered - yes I tested the other protocols (osc, tcp, udp)

**Comment by krocheck** [comment]
Yeah ... totally my bad.  Let's just go with a momentary lapse of reading abilities!

**Pull request merged**
