### PR TITLE
feat: step button type to replace latching

### PR DESCRIPTION
**Pull request by Julusian**
This is a rethink of the latch button behaviour. The code to handle latching has been full of precarious logic, that has been very buggy in the past (eg #995) #1589. It looked and felt like an after thought.

I have ripped out the existing logic and reimplemented it with some additional functionality.

First off, there is a slight behaviour change in that previously the release actions would be executed on button up, they are now executed on the down press. This was the source of a large amount of the complication.

Instead of latching, there is now a step button type. This is no longer simply a checkbox in the button styling, but a new option in the button type menu:
image

Once you have selected this 'step/latch' option, the actions tables are a little different to before. To begin with you have one called 'Step 1 actions', and there is an option below to add another. With this, you are not limited to having a latch, but can have a 3 or 4 way cycle. In fact, there is no limit. You could build a cue list as steps on a single button, and keep pressing the same button again and again #1626.

For example, this will cycle through 3 inputs on an atem:
localhost_3000_(1080p)

Also note, that on the right of the table heading is a group of buttons which allow for re-ordering and removing steps, as well as setting which one will be executed next (indicated in green)

Internal actions and feedbacks have been added ([separate PR](https://github.com/bitfocus/companion-module-bitfocus-companion/compare/feat/action-steps)):
image
image

Presets expect a slightly different structure, to match the changes. The 'old' format is handled and converted across, following the same rules as existing buttons being upgraded
Regular button:
image
Stepped button:
image

It isnt currently possible to convert between a regular and stepped button, due to the differing number of action sets they can have.

On the technical side, this changes the db format to have a single structure of 'action_sets' instead of 'actions' and 'release_actions'. Old databases and exports will be upgraded appropriately.
Presets in the old format are also 'upgraded' on the fly, so that they will work correctly.

### CODE REVIEW

**Comment by ltjost** [comment]
Thank you for cross referencing to my prior/next cue concepts.  I look forward to exploring this.  One item I am having a difficult time understanding through just reading this information is how the user will be able to jump to specific step live in case the planned sequential cue execution sequence is not sufficient to address the actual experience presented.  For example...in running a theatrical event, the cast skips ahead and/or then jumps back and the sequence needs to be adjusted on the fly...or at a rehearsal the sequence is totally not part of the plan.  Adding and removing cues seems to have been handled as has moving them around, which is excellent.  Again, looking forward to this!  Thanks.

**Comment by josephdadams** [comment]
@Julusian add "copy action" while you are at it :) #712 and #1132

**Comment by Julusian** [comment]
@josephdadams haha, soon. Once I start on that, it will end up with a bunch of changes in the area of button action management

@krocheck I am happy with this now. I have tested everything I can think of. Including importing some full and page exports I found on old issues.
The only thing I have left is to figure out a plan for upgrading existing 'is pressed' feedbacks if they were targeting a latch. I should do something, which will involve an upgradeScript and some extra data for the internal module to figure thing out.

**Comment by Julusian** [comment]
@MeestorX 

> Hoping that regular actions can be moved in and out of step actions,

I dont follow what you mean here. A button is either regular or stepped, and the actions are intentionally not aware of which it is. (I have plans for another new type of button)

> (along with copy/cut/paste of regular and step actions!).

That is another task on my growing todo list. Fairly near the top too

> I'll be interested to see how to create presets with step actions as well.

I have added some screenshots to the description showing the new format for writing presets

**Comment by MeestorX** [comment]
> @MeestorX
> 
> > Hoping that regular actions can be moved in and out of step actions,
> 
> I dont follow what you mean here. A button is either regular or stepped, and the actions are intentionally not aware of which it is. (I have plans for another new type of button)

Ah. I thought you have an action that happens on every push along with a step action. Didn't realize it was one or the other, thought you could combine them on one button.

However, you will need to be able to create step actions groups on one button, though e.g.
Group 1:
Step 1: Mute Ch 1
Step 2: UnMute Ch1

Group 2:
Step 1: Mute Ch 2
Step 2: UnMute Ch2

So that the 1st push Mutes Ch1 & Ch2, 2nd push Unmutes Ch1 & Ch2. Or maybe that's done a different way?

**Comment by jrviz** [comment]
Is there a derivation of this to allow a short, long and in-between timed button press structure rather than a sequence? e.g. use a timer value on button release to identify the Step set to trigger? 

I know that this is a different feature and has been requested but it may be that this new feature would be a good starting point.

Would need care on how delays are handled (perhaps they are always relative to guarantee a time sequence) , but I guess there is a similar issue for this button type if a step set has a long delay in it and a users keeps pressing the same key to stack up delayed steps as it sequences around.

**Comment by Julusian** [comment]
> Is there a derivation of this to allow a short, long and in-between timed button press structure rather than a sequence? e.g. use a timer value on button release to identify the Step set to trigger?
> 
> I know that this is a different feature and has been requested but it may be that this new feature would be a good starting point.

There is not. The structures introduced here will allow for that to be done, but I have not started on it yet. It is on my list and I have been thinking about how it will work, but I am holding off until this has been merged

**Comment by krocheck** [comment]
@Julusian for the feedback issue, add a checkbox on the left side under delay for "Indicate Bank as Pressed?" or something like that.

**Comment by krocheck** [comment]
@Julusian I was able to work through a merge.  I'm working on some post-merge errors and cleanup.

**Comment by Julusian** [comment]
@krocheck I fixed the feedback backwards compatability with a new option on the feedback (set in existing feedbacks via an upgrade script)
image
It treats the button as pressed if it is the step type and not on the first step.

A very quick test of this pr post your merge and it appears to be working

**Comment by krocheck** [comment]
This feature will be in a future release of Companion, but is currently only in the development/experimental track.  There are no accessible downloads of that track at this time.  Eventually it will be available in the public betas and thereafter a stable release.

**Pull request merged**
