### PR TITLE
feat(variable): add set variable to expression

### LINKED ISSUE #1723: about increase/decrease custom variable
Can I  increase/decrease the custom variable like attachment fig?

for example:
$(internal:custom_speed)+10

image

### PR DESCRIPTION
**Pull request by estilles**
This PR, combined with PR bitfocus/companion-module-bitfocus-companion#43, will add an action to `companion-module-bitfocus-companion` to 'Set custom variable to expression' such as:

```
$(internal:custom_counter) + 1
```

Valid operators include:
- Binary operators:
  - Addition: `a + b`
  - Subtraction: `a - b`
  - Multiplication: `a * b`
  - Division: `a / b`
  - Modulous: `a % b`
  - Exponentiation: `a ^ b`
- Unary operators:
  - Unary Negataion: `-a`
- Expression grouping:
  - Parenthesis: `(a + b) * c`

Resolves #1723
Signed-off-by: Johnny Estilles <johnny@estilles.com>

### CODE REVIEW

**Comment by Julusian** [comment]
I haven't given it a try, or read through the lib, but the companion code looks good.

I think we need to make sure to document well the syntax and support operations, to avoid using this being a game of trial and error

**Comment by estilles** [comment]
@Julusian ... agreed. I'll update the dynamic variables docs and add to the PR.

**Comment by estilles** [comment]
> I think we need to make sure to document well the syntax and support operations, to avoid using this being a game of trial and error

@Julusian As promised I've added docs. Please let me know your thoughts.

Also, I added a commit with a fix for a prettier issue in `lib/metrics.js`. Not related to my PR, but the failing format check for annoying me. :-)

**Comment by estilles** [comment]
Hey @Julusian! I wanted to ask if there anything else I should be doing in order to get this and bitfocus/companion-module-bitfocus-companion#43 merged. Are you okay with the docs I've added? Thanks!

**Comment by Julusian** [comment]
Sorry, I forgot to check back. It is merged now

**Pull request merged**
