### PR TITLE
feat: Improve module list search filtering

### PR DESCRIPTION
**Pull request by k-yle**
A lot of people give up when they search for a product but can't find it in the list. Searching for things like `black magic`, or `artnet` currently returns no results, which is unexpected. 

This PR improves the search filtering so that it matches items, even if spaces or punctuation isn't quite right. 

Also, should this PR target the `beta`, `develop`, or `master` branch? I couldn't find any guidelines

### CODE REVIEW

**Comment by Julusian** [comment]
Beta is the correct target.

Thanks. I think this is a good idea to do. Perhaps we should go further and use a library for fuzzy searching (such as https://fusejs.io/demo.html) to make it even better at searching?

**Comment by leeoniya** [comment]
some other fuzzy search options:

https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work

**Comment by k-yle** [comment]
sure, I've pushed a commit which uses `fuse.js`. I also tried `match-sorter` but that finds nothing with one of the original examples (an erroneous space in the word: `black magic`), and `uFuzzy` finds nothing when a hyphen is missing (e.g. `artnet` instead of `Art-Net`)

**Comment by leeoniya** [comment]
> and` uFuzzy` finds nothing when a hyphen is missing (e.g. `artnet` instead of `Art-Net`)

with default settings it won't. you can set adjust the settings to make it work:

```
intraChars: '.',   // allow any char to be inserted
intraIns: 1,       // at most once
```

**Comment by Julusian** [comment]
looking at the demo: https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,fuzzysort&search=mario%20adventures&intraChars=.&intraMode=1&intraIns=1

I am liking the look of fuzzysort. perhaps with a threshold of -100000 to filter out some junk

**Comment by k-yle** [comment]
I've switched it to `fuzzysort` which seems to work just as well

**Comment by leeoniya** [comment]
> perhaps with a threshold of -100000 to filter out some junk

this is precisely the problem uFuzzy tries to address :). if you try that cutoff for "magic", you'll get an incredible amount of garbage again:

image

if you toggle `outOfOrder`, uFuzzy will get you much better results:

https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,fuzzysort&search=mario%20adventures&intraChars=.&intraMode=1&intraIns=1&outOfOrder

image

**Pull request merged**
