### PR TITLE
feat: config field to enable the elgato plugin instead of scanning for local devices

### PR DESCRIPTION
**Pull request by Julusian**
This should resolve some common issues from users who try the elgato plugin instead of native streamdeck support. eg #1795

The plugin api is now disabled by default. It has a userconfig field to enable it, and doing so will stop companion attempting to connect to streamdecks by itself.
So users will have to explicitly choose which way they want it to work.

There are still some edge cases where the two can fight, but this should solve the bulk of the cases and will resolve some of the issues observed at startup once it has already been setup.

I don't know how we can do this without blanket disabling the plugin for everyone, hopefully we are ok with that being done.

This can also be used to disable streamdeck loading #1771

### CODE REVIEW

**Comment by krocheck** [comment]
Yeah, something like this has been needed.  I'm cautious to 'break' existing setups by requiring the WS api (I'm fine with the refactor) to be enabled.  I'm wondering if a dropdown of `Auto Detect`, `Enabled`, and `Disabled` would be better where new installs can be `Disabled` but upgrade would take `Auto Detect`.

Or as-is we attempt a one-time detection on upgrade to make a best effort to set this correctly for the user?

**Comment by Julusian** [comment]
I can understand your concern, I did think that at first.

I'm not convinced that auto-detect will be possible to make in a reliable fashion. Seeing as both bits of software fighting over streamdecks is a fairly regular issue that users post about, this suggests to me that we wont be able to rely on checking for the elgato software at companion startup, as we are already doing that. So unless we want to check every few minutes and disconnect from them all once we detect the software as running, I don't see auto-detect as being very reliable. And if we try to watch for the elgato software appearing, I expect it will lead to odd behaviour when we decide to disconnect from a streamdeck (eg Do we reset it to logo, or assume the elgato software was the last to draw?)
While this is an annoyance for all the plugin users, its a simple fix that just needs to be communicated to them well.

As for a one-time upgrade, we could look at the db and see if we have an entry for the plugin (indicating it has been used at some point before), but again that will often be wrong and makes the manual upgrade steps be more complex. This way it is a very simple note that every user needs to review of "If using the elgato plugin you need to enable it in the settings" rather than "If the elgato plugin stops working, make sure it is enabled in the settings. If direct streamdeck control stops working, make sure the plugin is disabled in the settings"

**Comment by krocheck** [comment]
@Julusian I pushed a commit that dynamically starts and stops the web server as the checkbox is ticked.  I didn't remove the "(Requires Companion restart)" since that's sort of true although they could just cycle the stream deck(s) on enable or once disabled do a rescan USB.

**Review by krocheck — APPROVED** [review]

**Comment by krocheck** [comment]
@Julusian your call when to hit 'Squash and merge` on this one.  I'm good, don't want to jump since I pushed some of my own code in.

**Comment by Julusian** [comment]
@isaiahfranco yeah, it got broken with this. Fixed in the latest build

**Comment by isaiahfranco** [comment]
Great! I'll have to give it a shot this week.

**Pull request merged**
