### PR TITLE
feat: remove yellow border

### PR DESCRIPTION
**Pull request by leonreucher**
Implemented https://github.com/bitfocus/companion/issues/1648
Added a new config option for disabling the yellow border around a pressed button, if the top bar is disabled.

### CODE REVIEW

**Comment by dnmeid** [comment]
I see that this is a user request and I also can imagine situations where you want to style your buttons yourself and don't want to have that border. But may I suggest a more sophisticated implementation.
I don't like to have yet another configuration checkbox, especially if then there are two checkboxes which influence the visual outcome. The "hide border" is only doing something if "show topbar" is off.
I'd prefer to have this combined in one dropdown, e.g. named `Indicators`. There could be `Topbar`, `Border` and `none` options.
The setting on the individual button can reflect this and and additionally offer `use default` like we have today.
Upgrading this in existing database from a boolean value to a dropdown is not that big problem.

Side bonus: we can offer bottom bar (#617) with same elegant ui and don't need another checkbox for that again.

**Comment by Julusian** [comment]
I agree with Dorian.
I did start and not quite finish that task for supporting moving the top bar to the bottom, which might be a useful reference on what is needed to support more options in thag dropdown. I didn't finish it though, probably not doing all of the upgrade/import bits (or maybe doing it but not testing it fully)
https://github.com/bitfocus/companion/compare/main...feat/move-topbar-to-bottom

**Comment by leonreucher** [comment]
Thanks for the feedback!
I adjusted the code and now you can choose between Top, Bottom, Border and None. It's working fine, I am only having trouble coding the upgrades from previous versions to the new layout.

**Comment by dnmeid** [comment]
You could do an upgrade function to upgrade the database. Look in companion/lib/Data/Upgrades/ and companion/lib/Data/Upgrade.ts
Other option is a rolling upgrade, that means the logic you are using would need to be able to cope with the old boolean value and the new enum (string?) value as well. Then there is no need to rewrite existing database values, they are just interpreted correct. In a new database or upon change of the setting, the new value is set.

Drawback of the upgrade script is that the users can't go back, i.e. the database will not be compatible with older Companion versions. Drawback of the rolling upgrade is that the logic of the upgrade is offloaded to different locations, including a dropdown, which actually should not do anything besides dropdown stuff.

**Comment by Julusian** [comment]
@leonreucher did you mean to push some more commits to this PR/branch?

**Comment by leonreucher** [comment]
@Julusian tbh. I was still not able to get the upgrade part ready and working. I'll close this PR and open a new one when I got it to working.

**Pull request closed without merging**
