### PR TITLE
feat: more than 99 pages #2003

### PR DESCRIPTION
**Pull request by Julusian**
Support more or less than 99 pages.

Fresh companion installations will start with 1 page, it is intended that users add as many pages as they need. Existing installations are unchanged, to avoid risking impacting users without them expecting it.

There is a new 'pages' tab in the right panel, which lists the pages with links to jump to a page, as well as to insert/add a page (at any position), and remove any page.
image

When adding a page, a modal is shown, to allow easily adding multiple and to encourage giving each new page a name

image

If when removing a page, a surface ends up out of bounds, it will be pushed to be within the new page count.

### TODO:
- [x] Importing a single page needs to be able to import to a new page (potentially just at the end for now?)
- [x] When adding a page, open a prompt to ask how many pages and the name to give each page

### Future:
* Some work should be done to make surfaces more sticky to pages when they are removed/reordered
* The actions/feedbacks should be improved to be able to reference a page by id. this is so that as the index of a page changes, actions and feedbacks can 'follow' that moving. (Import will need to take care to fix up these ids properly)
*  [Feature Request: Ability to rearrange existing pages #976](https://github.com/bitfocus/companion/issues/976)

### CODE REVIEW

**Comment by bryce-seifert** [comment]
@Julusian Just played around with this, seems to be working well. I'm not sure if it's in the scope of this pull, but the new Pages tab has me thinking about the following:

- Ability to bulk add pages. IE add 10 new pages at a time as opposed to individually, especially if all new instances are starting at 1
- Ability to reorder pages https://github.com/bitfocus/companion/issues/976 I feel like that could potentially be worked into this new Pages tab with up/down arrows?

And less of a priority, bit I'm wondering if there's a way to add a more obvious add / delete animation on the pages tab. It sort of pops on currently, but I think a quick fade in / out, with green or red background/text could help see exactly where a page was added/removed

**Comment by Julusian** [comment]
> @Julusian Just played around with this, seems to be working well. 

Thanks for trying it, Im glad it is working for you :)

> * Ability to bulk add pages. IE add 10 new pages at a time as opposed to individually, especially if all new instances are starting at 1

Yeah that would be reasonable. I guess a button next to the existing add at end button (or the insert ones too?) which will open a prompt. or should all the existing buttons prompt for how many to add?

> * Ability to reorder pages [Feature Request: Ability to rearrange existing pages #976](https://github.com/bitfocus/companion/issues/976) I feel like that could potentially be worked into this new Pages tab with up/down arrows?

Yeah, I'm leaving that out of this to try and avoid this PR becoming huge. It is one of the next things to do though

> And less of a priority, bit I'm wondering if there's a way to add a more obvious add / delete animation on the pages tab. It sort of pops on currently, but I think a quick fade in / out, with green or red background/text could help see exactly where a page was added/removed

that sounds beyond my ability of creating something that will look acceptable :laughing:  

but this does make me wonder, perhaps adding a page should always open a modal and it should prompt the user to give the new pages names. In the past the page names haven't been used for all that much (although their use has been growing gradually over time), perhaps we should be nudging the user to give them useful names?   
Then at the same time it would be easy to prompt the user to choose how many pages to insert

**Comment by bryce-seifert** [comment]
>  I guess a button next to the existing add at end button (or the insert ones too?) which will open a prompt. or should all the existing buttons prompt for how many to add?

My thought is using the existing button(s) with prompt, and if we page names are added there it could streamline that setup

**Comment by Julusian** [comment]
After leaving this alone for too long, I am satisfied that this chunk is complete.
There is still more to do to improve the support for dynamic page counts (see the 'future' heading in the description), which shall follow and should be done before this makes it into the betas

**Comment by smudge1977** [comment]
I'm not a Node or js person but it looks like the API still all runs on numbers for pages which I would guess would be the order pages are added in rather than been the name - so for example the common bank-press - I'm using UDP broadcasts to do the work:
https://github.com/bitfocus/companion/blob/13d9a2a738b287ef142ac615b4d916f96eabe065/companion/lib/Service/TcpUdpApi.js#L112

**Comment by Julusian** [comment]
@smudge1977 The api's have not been changed for this currently, I'm not sure how those changes should look currently.
But it will respect the order they are shown in the ui and the rest of the system

**Comment by reidwwall** [comment]
Hello,
I Cannot seem to find this feature in companion now.  I have tried looking in 3.2.2 AND and 3.3.0.  Am I missing something?

Thank You!

**Comment by dnmeid** [comment]
> Hello, I Cannot seem to find this feature in companion now. I have tried looking in 3.2.2 AND and 3.3.0. Am I missing something?

@reidwwall It is in the development branch, that means the experimental builds.

**Pull request merged**
