### PR TITLE
feat: boolean feedback invert #2547

### PR DESCRIPTION
**Pull request by Julusian**
This shows an 'Invert' checkbox for all boolean feedbacks, unless the feedback already has one (simple check for field of certain id).  

This will apply to all modules, the configurability requires an updated @companion-module/base

Shown here is a feedback with the new field applied, and one which already had an invert checkbox:
image

The behaviour of this is handled internally, with modules only being aware of this in their upgrade scripts. This is so that they can migrate users to/from this builtin invert field.

Modules are able to turn this invert field on and off, by setting the `showInvert` property on their feedbacks. By default we will auto-detect whether to show the field, but if set to true/false we will respect the specified value. Module developers will need to make sure to not break user configs when changing this.

Example upgrade snippet:
```js
	for (const feedback of props.feedbacks) {
		if (feedback.feedbackId === FeedbackId.DSKOnAir && feedback.options['invert'] !== undefined) {
			feedback.isInverted = !!feedback.options['invert']
			delete feedback.options['invert']
			result.updatedFeedbacks.push(feedback)
		}
	}
```

### CODE REVIEW

**Comment by istnv** [comment]
This solves #1649 as well.

**Comment by Julusian** [comment]
I feel like #1649 is already possible with the event `On condition becoming false`. But if not then yeah this will probably help

**Comment by istnv** [comment]
Both work. I think this is simpler/cleaner by acting directly on `true/false` instead of testing an expression.
Similar to `if (ok) {}` or `if (!ok) {}`vs `if (ok == true) {}` or `if (ok == false) {}`

**Comment by krocheck** [comment]
Since this is a static feature of booleans, I feel like my preference is to see it on the left under the learn option rather than inline with other options.  Happy for others to disagree, just my 2 cents.

**Comment by Julusian** [comment]
I have no problem with that.
I do think it will make things a little less consistent, as for a while some feedbacks will have an invert in the left and some in the right (depending on whether they define the invert field themselves). But going forward that should decrease as modules remove any invert fields they have added.
And we can always move it back later if it does prove too confusing.

Ill get that moved across. I shall also look into providing a helper function for upgrade scripts, to make it easier for modules to update their feedbacks. Maybe I should look into finding all the modules which implement invert fields already, so we can suggest they remove them.

**Pull request merged**
