### PR TITLE
Module: Upgraded epiphan-pearl

### PR DESCRIPTION
**Pull request by MarcHagen**
Release epiphan-pearl 1.0.1

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
Doesn't seem like package.json is updated with a new version numbe?

**Comment by MarcHagen** [comment]
@haakonnessjoen Yes correct, becuase @JeffreyDavidsz had already pushed something to the master branch while i work in the develop branch
To the version was already updated

**Comment by JeffreyDavidsz** [comment]
@MarcHagen  did you fork the Companion repo and do a pull request against that? You could just clone Companion, and fork the module you would like to alter. Then when you do a pull request it will go against that repo only. Not quite sure if this way could create conflicts in references. @haakonnessjoen

**Comment by haakonnessjoen** [comment]
@JeffreyDavidsz He has worked in a separate repo. This is just a pull request for the inclusion of the module.

**Comment by MarcHagen** [comment]
Well a update of the sub-module actually

**Pull request merged**
