### PR TITLE
feat: Add fontsize to Satellite API

### PR DESCRIPTION
**Pull request by elianterelle**
This PR adds Fontsize as optional streamed data to the Sattelite API.
I added a new Flag `FONTSIZE` for the `ADD-DEVICE` command, similar to the already existing `TEXT`, `COLOR`, ...
if this flag is set to true, the fontsize is passed on every `KEY-STATE` message.

If this gets merged, the wiki would need to be updated at two places:
- Messages to send -> Adding a satellite device -> Optional parameters:
`FONTSIZE` - true/false whether you want to be streamed button font size for display on the buttons (default false) 

- Messages to receive -> State change for key:
`FONTSIZE` Font size as an integer for the key. This is only sent for devices which were added where `FONTSIZE` was true

### CODE REVIEW

**Comment by krocheck** [comment]
Can you as part of this PR, since I’m not aware of any other planned changes to this API, in the service class increment the version to 1.4.0 and document the new param.

**Comment by elianterelle** [comment]
Done! Hope the force push was ok, don't have that much experience with pull requests but thought it would be nicer as a single commit and seems to have updated the pr correctly.

**Comment by krocheck** [comment]
@elianterelle my quick review of the code seems to indicate the COLORS flag sends only bgcolor instead of both bgcolor and [font]color.  Is this accurate and something you would want to address as well?

Our workflow is squash and merge, so cleaning up like that isn’t really necessary.

**Comment by elianterelle** [comment]
That's correct, for my usecase it doesn't matter as i'm using monochrome displays, but i could add this. Then the only missing parameters would be text alignment i think, so if i we add fontcolor, why not add that as well. I'd suggest FONTCOLOR and TEXTALIGN for the parameter names(I'm not a native english speaker but i think that's the correct distinction between Font and Text similar to how it's done in CSS for example)?

**Comment by krocheck** [comment]
@Julusian do you have an opinion here?

**Comment by Julusian** [comment]
I am not certain on this but I am wondering if this should be included as part of the `TEXT=1` option, or perhaps `TEXT-STYLE=1`? 
While both of these would cause us to send more data than may be necessary to clients, it limits the number of options we have at the time of adding the device

**Comment by elianterelle** [comment]
The only issue i see in this is that it could potentially be a breaking change in the sense that the KEY-STATE message gets considerably longer, which is probably irrelevant with dynamically typed languages like javascript, but for example i use the satellite api on a microcontroller programmed in C, so my buffer for incoming messages has a fixed length. On the other side, the satellite api docs already states that more parameters can be added over time.

**Comment by elianterelle** [comment]
That wouldn't be an issue with a new flag like the `TEXT-STYLE` you mentioned.

**Comment by Julusian** [comment]
> Any update on this? Should i go ahead and implement `text-align` and `font-color` in addition to `font-size` with a combined flag `TEXT-STYLE`?

I think it would be good to get it under a `TEXT-STYLE` flag, but the other properties dont need to be defined yet. If theyre not needed, it would be better to leave them be for now, as there is a plan to overhaul the graphics generation which may change how some of these things will work

**Comment by elianterelle** [comment]
Done. I called it `TEXT_STYLE` instead of `TEXT-STYLE` to match the other properties(`PRODUCT_NAME`, `KEYS_PER_ROW`,..) and also changed the property sent to the device from "FONTSIZE" to "FONT_SIZE". Let me know if there's anything else to do on this

**Comment by Julusian** [comment]
Thanks!
I've also pulled this into beta too

**Pull request merged**
