### PR TITLE
Add an upgrade test script

### PR DESCRIPTION
**Pull request by peternewman**
Currently this runs if used standalone (with the describe/it/expect bits commented out, but if I run it via Jest it hits the garbage collector. Any idea what I've done wrong @Julusian ?

```
node --trace-warnings --experimental-vm-modules node_modules/jest/bin/jest.js v2tov3-upgradeStartup

 RUNS  test/v2tov3-upgradeStartup.test.js

<--- Last few GCs --->

[355375:0x18ad31b0]   148005 ms: Mark-sweep (reduce) 2045.4 (2083.2) -> 2044.1 (2083.2) MB, 4279.8 / 0.0 ms  (average mu = 0.119, current mu = 0.004) allocation failure; scavenge might not succeed
[355375:0x18ad31b0]   152201 ms: Mark-sweep (reduce) 2045.6 (2083.5) -> 2044.7 (2083.7) MB, 4178.4 / 0.0 ms  (average mu = 0.065, current mu = 0.004) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb69e0c node::Abort() [node]
 2: 0xa8df18  [node]
 3: 0xd34750 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd34920 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf12eac  [node]
 6: 0xf13b14 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xf24064  [node]
 8: 0xf24c28 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf00fc0 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xf01f98 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xee4c28 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
12: 0x128b354 v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
13: 0x166fd8c  [node]
Aborted
```

### CODE REVIEW

**Comment by Julusian** [comment]
Interestingly I am not getting the same failure..
Instead it actually runs, and has a test failure
```
  console.log
    Got:

      at log (test/v2tov3-upgradeStartup.test.js:12:10)

  console.log
    { page_config_version: 3 }

      at log (test/v2tov3-upgradeStartup.test.js:13:10)

silly: db_get(bank) {"source":"Data/Database"}
silly: db_get(bank_actions) {"source":"Data/Database"}
silly: db_get(bank_release_actions) {"source":"Data/Database"}
silly: db_get(bank_rotate_left_actions) {"source":"Data/Database"}
silly: db_get(bank_rotate_right_actions) {"source":"Data/Database"}
silly: db_del (bank_actions) {"source":"Data/Database"}
silly: db_del (bank_release_actions) {"source":"Data/Database"}
silly: db_get(bank) {"source":"Data/Database"}
silly: db_get(feedbacks) {"source":"Data/Database"}
silly: db_del (bank) {"source":"Data/Database"}
silly: db_del (feedbacks) {"source":"Data/Database"}
silly: db_del (bank_action_sets) {"source":"Data/Database"}
silly: db_set(controls, [object Object]) {"source":"Data/Database"}
silly: db_get(controls) {"source":"Data/Database"}
silly: db_get(deviceconfig) {"source":"Data/Database"}
 FAIL  test/v2tov3-upgradeStartup.test.js
  upgrade
    ✕ empty (54 ms)

  ● upgrade › empty

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)

      328 |
      329 |     // Ignore satellite for now, as that has not been updated, and no colon
    > 330 |     const keys = Object.keys(devices).filter((d) => !d.startsWith('satellite-') && d.indexOf(':') === -1)
          |                         ^
      331 |
      332 |     for (const key of keys) {
      333 |             const key2 = key.trim()

      at keys (lib/Data/Upgrades/v2tov3.js:330:22)
      at Object.convertSurfacesToV3 [as upgradeStartup] (lib/Data/Upgrades/v2tov3.js:355:2)
      at Object.upgradeStartup (test/v2tov3-upgradeStartup.test.js:21:25)

Test Suites: 1 failed, 4 passed, 5 total
Tests:       1 failed, 92 passed, 93 total
Snapshots:   0 total
Time:        4.031 s
```

My only theory is that it is pulling in too much of something, perhaps by slimming things down a bit will help?
I think there are some semi cyclical import loops in these files, that might need straightening out to make jest happy. perhaps that is related?

**Comment by peternewman** [comment]
> Interestingly I am not getting the same failure..

Well it's not just me as the CI fails too (some versions of node or something maybe?):
https://github.com/bitfocus/companion/actions/runs/6331403527/job/17195896291

> Instead it actually runs, and has a test failure

Yes, I'm pretty certain that's this again where this all started https://github.com/bitfocus/companion/issues/2557 and was again fixed by https://github.com/bitfocus/companion/commit/64d5b8e8c2fdeb427dc94623cf46029f592aee85 when I tried locally, but I left it in as a good test for now! I think the only reason I didn't see it testing locally was because I had a previous v3 config (whereas 3.99 is treated as v4 I think I saw somewhere). I've not traced where the problem line was added to confirm if it affects earlier releases too.

I'm also aware my expect isn't right yet, but it's a bit irrelevant if the test doesn't even run itself.

> My only theory is that it is pulling in too much of something, perhaps by slimming things down a bit will help? I think there are some semi cyclical import loops in these files, that might need straightening out to make jest happy. perhaps that is related?

Yeah I had some issues at first trying to import things initially and them not being defined, until I added something further up the stack instead.

**Comment by Julusian** [comment]
> Well it's not just me as the CI fails too (some versions of node or something maybe?):

Yeah it is, but I can't figure out what is different.
I am running the exact same version of nodejs, also on linux, also x64. I have tried to limit the amount of memory available to it, but that has no impact, also execution terminates much quicker on my machine so it kinda feels like it is ending up in an infinite loop in the ci, which mine is not?

I've gone with a radical strategy of replacing jest with a different test runner. Trying out the new nodejs builtin runner. 
This appears to be happier, instead failing n the `BUILD` file being missing. Which confirms that in jest it was not getting through all the imports in Registry.js.

I just need to figure out how to replace the `if (process.env.JEST_WORKER_ID)` checks with something compatible, then the test should run

**Comment by peternewman** [comment]
> Yeah it is, but I can't figure out what is different. I am running the exact same version of nodejs, also on linux, also x64. I have tried to limit the amount of memory available to it, but that has no impact, also execution terminates much quicker on my machine so it kinda feels like it is ending up in an infinite loop in the ci, which mine is not?

A different local version of Jest?

> I've tried a radical strategy of replacing jest with a different test runner. Trying out the new nodejs builtin runner. This appears to be happier, instead failing n the `BUILD` file being missing. Which confirms that in jest it was not getting through all the imports in Registry.js.

🚀 

> I just need to figure out how to replace the `if (process.env.JEST_WORKER_ID)` checks with something compatible, then the test should run. Although I would like to stick with jest, but its ESM support is pretty bad which I suspect is the issue we are hitting here

Depending on how keen you are to keep jest, we could just use the nodejs runner for this test/others that don't work in jest? Although I appreciate that will be more effort for developers to get across two systems.

**Comment by Julusian** [comment]
Fixed! 

I managed to reproduce (or get closer) by running jest with `--no-cache`.
And by forcing nodejs to have a higher memory limit when running jest it now works.

I should probably put some more effort into improving the imports for this, but this will do for now

**Comment by peternewman** [comment]
Thanks for solving the issue. I've fixed the test to match too @Julusian .

N.B. I'm pretty certain this edge cases is broken in master too, given this commit is missing from there:
https://github.com/bitfocus/companion/commit/64d5b8e8c2fdeb427dc94623cf46029f592aee85

So I've opened #2615 to fix that.

**Pull request merged**
